region                          = "us-east-1"
env                             = "Dev"   # Environment Dev or QA
cluster_name                    = "EKS-30Jun"
eks_version                     = "1.19"
cluster_subnet_ids              = ["subnet-XXXX", "subnet-XXXX"]
cluster_role_arn                = "arn:aws:iam::XXXX:role/Analytics-Eks"
node_subnet_ids                 = ["subnet-XXXX"]
security_groups                 = ["sg-XXXX"]
node_role_arn                   = "arn:aws:iam::XXXX:role/Analytics-EKSNode"
instance_type			= "r5.large"
storage_size			= 20
key_pair			= "anrathore"
ssm_param_name			= "amazon-2-eks"
desired_cluster_size            = 2
max_cluster_size                = 2
min_cluster_size                = 2
app_id                          = "xxxx"
cost_center                     = "xxxxx" 
patch_group                     = "amazon-linux-2"
